/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotpVerifyRouteImport } from './routes/totp-verify'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DeniedRouteImport } from './routes/denied'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppDriveRouteImport } from './routes/_app/drive'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app/documents/index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppDocumentsNewRouteImport } from './routes/_app/documents/new'
import { Route as AppDocumentsDocIdRouteImport } from './routes/_app/documents/$docId'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppAdminPoliciesRouteImport } from './routes/_app/admin/policies'
import { Route as AppAdminCronRouteImport } from './routes/_app/admin/cron'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppAdminUsersGroupsRouteImport } from './routes/_app/admin/users/groups'
import { Route as AppProjectsProjectIdIssuesIssueIdRouteImport } from './routes/_app/projects/$projectId.issues.$issueId'
import { Route as AppProjectsProjectIdIssuesIssueIdFullRouteImport } from './routes/_app/projects/$projectId_.issues.$issueId.full'

const TotpVerifyRoute = TotpVerifyRouteImport.update({
  id: '/totp-verify',
  path: '/totp-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DeniedRoute = DeniedRouteImport.update({
  id: '/denied',
  path: '/denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/overview.lazy').then((d) => d.Route))
const AppDriveRoute = AppDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/drive.lazy').then((d) => d.Route))
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/documents.lazy').then((d) => d.Route),
)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/projects/index.lazy').then((d) => d.Route),
)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDocumentsRoute,
} as any).lazy(() =>
  import('./routes/_app/documents/index.lazy').then((d) => d.Route),
)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/projects/$projectId.lazy').then((d) => d.Route),
)
const AppDocumentsNewRoute = AppDocumentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDocumentsRoute,
} as any).lazy(() =>
  import('./routes/_app/documents/new.lazy').then((d) => d.Route),
)
const AppDocumentsDocIdRoute = AppDocumentsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => AppDocumentsRoute,
} as any).lazy(() =>
  import('./routes/_app/documents/$docId.lazy').then((d) => d.Route),
)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/settings.lazy').then((d) => d.Route),
)
const AppAdminPoliciesRoute = AppAdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/policies.lazy').then((d) => d.Route),
)
const AppAdminCronRoute = AppAdminCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/cron.lazy').then((d) => d.Route),
)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/audit.lazy').then((d) => d.Route),
)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminUsersRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/users/index.lazy').then((d) => d.Route),
)
const AppAdminUsersGroupsRoute = AppAdminUsersGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppAdminUsersRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/users/groups.lazy').then((d) => d.Route),
)
const AppProjectsProjectIdIssuesIssueIdRoute =
  AppProjectsProjectIdIssuesIssueIdRouteImport.update({
    id: '/issues/$issueId',
    path: '/issues/$issueId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects/$projectId.issues.$issueId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectIdIssuesIssueIdFullRoute =
  AppProjectsProjectIdIssuesIssueIdFullRouteImport.update({
    id: '/projects/$projectId_/issues/$issueId/full',
    path: '/projects/$projectId/issues/$issueId/full',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects/$projectId_.issues.$issueId.full.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/denied': typeof DeniedRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/totp-verify': typeof TotpVerifyRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/documents': typeof AppDocumentsRouteWithChildren
  '/drive': typeof AppDriveRoute
  '/overview': typeof AppOverviewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/cron': typeof AppAdminCronRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/documents/$docId': typeof AppDocumentsDocIdRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/documents/': typeof AppDocumentsIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/admin/users/groups': typeof AppAdminUsersGroupsRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/projects/$projectId/issues/$issueId/full': typeof AppProjectsProjectIdIssuesIssueIdFullRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/denied': typeof DeniedRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/totp-verify': typeof TotpVerifyRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/drive': typeof AppDriveRoute
  '/overview': typeof AppOverviewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/cron': typeof AppAdminCronRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/documents/$docId': typeof AppDocumentsDocIdRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/documents': typeof AppDocumentsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/admin/users/groups': typeof AppAdminUsersGroupsRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/projects/$projectId/issues/$issueId/full': typeof AppProjectsProjectIdIssuesIssueIdFullRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/denied': typeof DeniedRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/totp-verify': typeof TotpVerifyRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/documents': typeof AppDocumentsRouteWithChildren
  '/_app/drive': typeof AppDriveRoute
  '/_app/overview': typeof AppOverviewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/cron': typeof AppAdminCronRoute
  '/_app/admin/policies': typeof AppAdminPoliciesRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/_app/documents/$docId': typeof AppDocumentsDocIdRoute
  '/_app/documents/new': typeof AppDocumentsNewRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/admin/users/groups': typeof AppAdminUsersGroupsRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/_app/projects/$projectId_/issues/$issueId/full': typeof AppProjectsProjectIdIssuesIssueIdFullRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/denied'
    | '/error'
    | '/login'
    | '/totp-verify'
    | '/admin'
    | '/documents'
    | '/drive'
    | '/overview'
    | '/shared/$token'
    | '/admin/audit'
    | '/admin/cron'
    | '/admin/policies'
    | '/admin/settings'
    | '/admin/users'
    | '/documents/$docId'
    | '/documents/new'
    | '/projects/$projectId'
    | '/documents/'
    | '/projects/'
    | '/admin/users/groups'
    | '/admin/users/'
    | '/projects/$projectId/issues/$issueId'
    | '/projects/$projectId/issues/$issueId/full'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/denied'
    | '/error'
    | '/login'
    | '/totp-verify'
    | '/admin'
    | '/drive'
    | '/overview'
    | '/shared/$token'
    | '/admin/audit'
    | '/admin/cron'
    | '/admin/policies'
    | '/admin/settings'
    | '/documents/$docId'
    | '/documents/new'
    | '/projects/$projectId'
    | '/documents'
    | '/projects'
    | '/admin/users/groups'
    | '/admin/users'
    | '/projects/$projectId/issues/$issueId'
    | '/projects/$projectId/issues/$issueId/full'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/denied'
    | '/error'
    | '/login'
    | '/totp-verify'
    | '/_app/admin'
    | '/_app/documents'
    | '/_app/drive'
    | '/_app/overview'
    | '/shared/$token'
    | '/_app/admin/audit'
    | '/_app/admin/cron'
    | '/_app/admin/policies'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/documents/$docId'
    | '/_app/documents/new'
    | '/_app/projects/$projectId'
    | '/_app/documents/'
    | '/_app/projects/'
    | '/_app/admin/users/groups'
    | '/_app/admin/users/'
    | '/_app/projects/$projectId/issues/$issueId'
    | '/_app/projects/$projectId_/issues/$issueId/full'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DeniedRoute: typeof DeniedRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  TotpVerifyRoute: typeof TotpVerifyRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totp-verify': {
      id: '/totp-verify'
      path: '/totp-verify'
      fullPath: '/totp-verify'
      preLoaderRoute: typeof TotpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denied': {
      id: '/denied'
      path: '/denied'
      fullPath: '/denied'
      preLoaderRoute: typeof DeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drive': {
      id: '/_app/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof AppDriveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/new': {
      id: '/_app/documents/new'
      path: '/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AppDocumentsNewRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/documents/$docId': {
      id: '/_app/documents/$docId'
      path: '/$docId'
      fullPath: '/documents/$docId'
      preLoaderRoute: typeof AppDocumentsDocIdRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/policies': {
      id: '/_app/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AppAdminPoliciesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/cron': {
      id: '/_app/admin/cron'
      path: '/cron'
      fullPath: '/admin/cron'
      preLoaderRoute: typeof AppAdminCronRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/admin/users/groups': {
      id: '/_app/admin/users/groups'
      path: '/groups'
      fullPath: '/admin/users/groups'
      preLoaderRoute: typeof AppAdminUsersGroupsRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/projects/$projectId/issues/$issueId': {
      id: '/_app/projects/$projectId/issues/$issueId'
      path: '/issues/$issueId'
      fullPath: '/projects/$projectId/issues/$issueId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId_/issues/$issueId/full': {
      id: '/_app/projects/$projectId_/issues/$issueId/full'
      path: '/projects/$projectId/issues/$issueId/full'
      fullPath: '/projects/$projectId/issues/$issueId/full'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdFullRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminUsersRouteChildren {
  AppAdminUsersGroupsRoute: typeof AppAdminUsersGroupsRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersGroupsRoute: AppAdminUsersGroupsRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminCronRoute: typeof AppAdminCronRoute
  AppAdminPoliciesRoute: typeof AppAdminPoliciesRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminCronRoute: AppAdminCronRoute,
  AppAdminPoliciesRoute: AppAdminPoliciesRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppDocumentsRouteChildren {
  AppDocumentsDocIdRoute: typeof AppDocumentsDocIdRoute
  AppDocumentsNewRoute: typeof AppDocumentsNewRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
}

const AppDocumentsRouteChildren: AppDocumentsRouteChildren = {
  AppDocumentsDocIdRoute: AppDocumentsDocIdRoute,
  AppDocumentsNewRoute: AppDocumentsNewRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
}

const AppDocumentsRouteWithChildren = AppDocumentsRoute._addFileChildren(
  AppDocumentsRouteChildren,
)

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdIssuesIssueIdRoute: typeof AppProjectsProjectIdIssuesIssueIdRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdIssuesIssueIdRoute:
    AppProjectsProjectIdIssuesIssueIdRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDocumentsRoute: typeof AppDocumentsRouteWithChildren
  AppDriveRoute: typeof AppDriveRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppProjectsProjectIdIssuesIssueIdFullRoute: typeof AppProjectsProjectIdIssuesIssueIdFullRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDocumentsRoute: AppDocumentsRouteWithChildren,
  AppDriveRoute: AppDriveRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppProjectsProjectIdIssuesIssueIdFullRoute:
    AppProjectsProjectIdIssuesIssueIdFullRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DeniedRoute: DeniedRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  TotpVerifyRoute: TotpVerifyRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
