/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TotpVerifyRouteImport } from './routes/totp-verify'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as DeniedRouteImport } from './routes/denied'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SharedTokenRouteImport } from './routes/shared.$token'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppDriveRouteImport } from './routes/_app/drive'
import { Route as AppDocumentsRouteImport } from './routes/_app/documents'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppShipsIndexRouteImport } from './routes/_app/ships/index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppDocumentsIndexRouteImport } from './routes/_app/documents/index'
import { Route as AppContactsIndexRouteImport } from './routes/_app/contacts/index'
import { Route as AppShipsShipIdRouteImport } from './routes/_app/ships/$shipId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppDocumentsNewRouteImport } from './routes/_app/documents/new'
import { Route as AppDocumentsDocIdRouteImport } from './routes/_app/documents/$docId'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin/users'
import { Route as AppAdminSettingsRouteImport } from './routes/_app/admin/settings'
import { Route as AppAdminPoliciesRouteImport } from './routes/_app/admin/policies'
import { Route as AppAdminCronRouteImport } from './routes/_app/admin/cron'
import { Route as AppAdminAuditRouteImport } from './routes/_app/admin/audit'
import { Route as AppProjectsProjectIdIndexRouteImport } from './routes/_app/projects/$projectId.index'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app/admin/users/index'
import { Route as AppProjectsProjectIdProcurementsRouteImport } from './routes/_app/projects/$projectId.procurements'
import { Route as AppProjectsProjectIdIssuesRouteImport } from './routes/_app/projects/$projectId.issues'
import { Route as AppProjectsProjectIdFilesRouteImport } from './routes/_app/projects/$projectId.files'
import { Route as AppDriveSheetEntryIdRouteImport } from './routes/_app/drive_.sheet.$entryId'
import { Route as AppAdminUsersGroupsRouteImport } from './routes/_app/admin/users/groups'
import { Route as AppProjectsProjectIdProcurementsProcurementIdRouteImport } from './routes/_app/projects/$projectId.procurements.$procurementId'
import { Route as AppProjectsProjectIdIssuesIssueIdRouteImport } from './routes/_app/projects/$projectId.issues.$issueId'
import { Route as AppProjectsProjectIdFromShipIdRouteImport } from './routes/_app/projects/$projectId.from.$shipId'
import { Route as AppProjectsProjectIdProcurementsProcurementIdFullRouteImport } from './routes/_app/projects/$projectId_.procurements.$procurementId.full'
import { Route as AppProjectsProjectIdIssuesIssueIdFullRouteImport } from './routes/_app/projects/$projectId_.issues.$issueId.full'

const TotpVerifyRoute = TotpVerifyRouteImport.update({
  id: '/totp-verify',
  path: '/totp-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const DeniedRoute = DeniedRouteImport.update({
  id: '/denied',
  path: '/denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenRoute = SharedTokenRouteImport.update({
  id: '/shared/$token',
  path: '/shared/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/overview.lazy').then((d) => d.Route))
const AppDriveRoute = AppDriveRouteImport.update({
  id: '/drive',
  path: '/drive',
  getParentRoute: () => AppRoute,
} as any).lazy(() => import('./routes/_app/drive.lazy').then((d) => d.Route))
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/documents.lazy').then((d) => d.Route),
)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppShipsIndexRoute = AppShipsIndexRouteImport.update({
  id: '/ships/',
  path: '/ships/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/ships/index.lazy').then((d) => d.Route),
)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/projects/index.lazy').then((d) => d.Route),
)
const AppDocumentsIndexRoute = AppDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDocumentsRoute,
} as any).lazy(() =>
  import('./routes/_app/documents/index.lazy').then((d) => d.Route),
)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/contacts/index.lazy').then((d) => d.Route),
)
const AppShipsShipIdRoute = AppShipsShipIdRouteImport.update({
  id: '/ships/$shipId',
  path: '/ships/$shipId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/ships/$shipId.lazy').then((d) => d.Route),
)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/projects/$projectId.lazy').then((d) => d.Route),
)
const AppDocumentsNewRoute = AppDocumentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppDocumentsRoute,
} as any).lazy(() =>
  import('./routes/_app/documents/new.lazy').then((d) => d.Route),
)
const AppDocumentsDocIdRoute = AppDocumentsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => AppDocumentsRoute,
} as any).lazy(() =>
  import('./routes/_app/documents/$docId.lazy').then((d) => d.Route),
)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/settings.lazy').then((d) => d.Route),
)
const AppAdminPoliciesRoute = AppAdminPoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/policies.lazy').then((d) => d.Route),
)
const AppAdminCronRoute = AppAdminCronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/cron.lazy').then((d) => d.Route),
)
const AppAdminAuditRoute = AppAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AppAdminRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/audit.lazy').then((d) => d.Route),
)
const AppProjectsProjectIdIndexRoute =
  AppProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects/$projectId.index.lazy').then((d) => d.Route),
  )
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAdminUsersRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/users/index.lazy').then((d) => d.Route),
)
const AppProjectsProjectIdProcurementsRoute =
  AppProjectsProjectIdProcurementsRouteImport.update({
    id: '/procurements',
    path: '/procurements',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects/$projectId.procurements.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectIdIssuesRoute =
  AppProjectsProjectIdIssuesRouteImport.update({
    id: '/issues',
    path: '/issues',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects/$projectId.issues.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectIdFilesRoute =
  AppProjectsProjectIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects/$projectId.files.lazy').then((d) => d.Route),
  )
const AppDriveSheetEntryIdRoute = AppDriveSheetEntryIdRouteImport.update({
  id: '/drive_/sheet/$entryId',
  path: '/drive/sheet/$entryId',
  getParentRoute: () => AppRoute,
} as any).lazy(() =>
  import('./routes/_app/drive_.sheet.$entryId.lazy').then((d) => d.Route),
)
const AppAdminUsersGroupsRoute = AppAdminUsersGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppAdminUsersRoute,
} as any).lazy(() =>
  import('./routes/_app/admin/users/groups.lazy').then((d) => d.Route),
)
const AppProjectsProjectIdProcurementsProcurementIdRoute =
  AppProjectsProjectIdProcurementsProcurementIdRouteImport.update({
    id: '/$procurementId',
    path: '/$procurementId',
    getParentRoute: () => AppProjectsProjectIdProcurementsRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects/$projectId.procurements.$procurementId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectIdIssuesIssueIdRoute =
  AppProjectsProjectIdIssuesIssueIdRouteImport.update({
    id: '/$issueId',
    path: '/$issueId',
    getParentRoute: () => AppProjectsProjectIdIssuesRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects/$projectId.issues.$issueId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectIdFromShipIdRoute =
  AppProjectsProjectIdFromShipIdRouteImport.update({
    id: '/from/$shipId',
    path: '/from/$shipId',
    getParentRoute: () => AppProjectsProjectIdRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects/$projectId.from.$shipId.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectIdProcurementsProcurementIdFullRoute =
  AppProjectsProjectIdProcurementsProcurementIdFullRouteImport.update({
    id: '/projects/$projectId_/procurements/$procurementId/full',
    path: '/projects/$projectId/procurements/$procurementId/full',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects/$projectId_.procurements.$procurementId.full.lazy').then(
      (d) => d.Route,
    ),
  )
const AppProjectsProjectIdIssuesIssueIdFullRoute =
  AppProjectsProjectIdIssuesIssueIdFullRouteImport.update({
    id: '/projects/$projectId_/issues/$issueId/full',
    path: '/projects/$projectId/issues/$issueId/full',
    getParentRoute: () => AppRoute,
  } as any).lazy(() =>
    import('./routes/_app/projects/$projectId_.issues.$issueId.full.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/denied': typeof DeniedRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/totp-verify': typeof TotpVerifyRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/documents': typeof AppDocumentsRouteWithChildren
  '/drive': typeof AppDriveRoute
  '/overview': typeof AppOverviewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/cron': typeof AppAdminCronRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/admin/users': typeof AppAdminUsersRouteWithChildren
  '/documents/$docId': typeof AppDocumentsDocIdRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/ships/$shipId': typeof AppShipsShipIdRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/documents/': typeof AppDocumentsIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/ships/': typeof AppShipsIndexRoute
  '/admin/users/groups': typeof AppAdminUsersGroupsRoute
  '/drive/sheet/$entryId': typeof AppDriveSheetEntryIdRoute
  '/projects/$projectId/files': typeof AppProjectsProjectIdFilesRoute
  '/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRouteWithChildren
  '/projects/$projectId/procurements': typeof AppProjectsProjectIdProcurementsRouteWithChildren
  '/admin/users/': typeof AppAdminUsersIndexRoute
  '/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/from/$shipId': typeof AppProjectsProjectIdFromShipIdRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/projects/$projectId/procurements/$procurementId': typeof AppProjectsProjectIdProcurementsProcurementIdRoute
  '/projects/$projectId/issues/$issueId/full': typeof AppProjectsProjectIdIssuesIssueIdFullRoute
  '/projects/$projectId/procurements/$procurementId/full': typeof AppProjectsProjectIdProcurementsProcurementIdFullRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/denied': typeof DeniedRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/totp-verify': typeof TotpVerifyRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/drive': typeof AppDriveRoute
  '/overview': typeof AppOverviewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/admin/audit': typeof AppAdminAuditRoute
  '/admin/cron': typeof AppAdminCronRoute
  '/admin/policies': typeof AppAdminPoliciesRoute
  '/admin/settings': typeof AppAdminSettingsRoute
  '/documents/$docId': typeof AppDocumentsDocIdRoute
  '/documents/new': typeof AppDocumentsNewRoute
  '/ships/$shipId': typeof AppShipsShipIdRoute
  '/contacts': typeof AppContactsIndexRoute
  '/documents': typeof AppDocumentsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/ships': typeof AppShipsIndexRoute
  '/admin/users/groups': typeof AppAdminUsersGroupsRoute
  '/drive/sheet/$entryId': typeof AppDriveSheetEntryIdRoute
  '/projects/$projectId/files': typeof AppProjectsProjectIdFilesRoute
  '/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRouteWithChildren
  '/projects/$projectId/procurements': typeof AppProjectsProjectIdProcurementsRouteWithChildren
  '/admin/users': typeof AppAdminUsersIndexRoute
  '/projects/$projectId': typeof AppProjectsProjectIdIndexRoute
  '/projects/$projectId/from/$shipId': typeof AppProjectsProjectIdFromShipIdRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/projects/$projectId/procurements/$procurementId': typeof AppProjectsProjectIdProcurementsProcurementIdRoute
  '/projects/$projectId/issues/$issueId/full': typeof AppProjectsProjectIdIssuesIssueIdFullRoute
  '/projects/$projectId/procurements/$procurementId/full': typeof AppProjectsProjectIdProcurementsProcurementIdFullRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/denied': typeof DeniedRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/totp-verify': typeof TotpVerifyRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/documents': typeof AppDocumentsRouteWithChildren
  '/_app/drive': typeof AppDriveRoute
  '/_app/overview': typeof AppOverviewRoute
  '/shared/$token': typeof SharedTokenRoute
  '/_app/admin/audit': typeof AppAdminAuditRoute
  '/_app/admin/cron': typeof AppAdminCronRoute
  '/_app/admin/policies': typeof AppAdminPoliciesRoute
  '/_app/admin/settings': typeof AppAdminSettingsRoute
  '/_app/admin/users': typeof AppAdminUsersRouteWithChildren
  '/_app/documents/$docId': typeof AppDocumentsDocIdRoute
  '/_app/documents/new': typeof AppDocumentsNewRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRouteWithChildren
  '/_app/ships/$shipId': typeof AppShipsShipIdRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/documents/': typeof AppDocumentsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/ships/': typeof AppShipsIndexRoute
  '/_app/admin/users/groups': typeof AppAdminUsersGroupsRoute
  '/_app/drive_/sheet/$entryId': typeof AppDriveSheetEntryIdRoute
  '/_app/projects/$projectId/files': typeof AppProjectsProjectIdFilesRoute
  '/_app/projects/$projectId/issues': typeof AppProjectsProjectIdIssuesRouteWithChildren
  '/_app/projects/$projectId/procurements': typeof AppProjectsProjectIdProcurementsRouteWithChildren
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
  '/_app/projects/$projectId/': typeof AppProjectsProjectIdIndexRoute
  '/_app/projects/$projectId/from/$shipId': typeof AppProjectsProjectIdFromShipIdRoute
  '/_app/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/_app/projects/$projectId/procurements/$procurementId': typeof AppProjectsProjectIdProcurementsProcurementIdRoute
  '/_app/projects/$projectId_/issues/$issueId/full': typeof AppProjectsProjectIdIssuesIssueIdFullRoute
  '/_app/projects/$projectId_/procurements/$procurementId/full': typeof AppProjectsProjectIdProcurementsProcurementIdFullRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/denied'
    | '/error'
    | '/login'
    | '/totp-verify'
    | '/admin'
    | '/documents'
    | '/drive'
    | '/overview'
    | '/shared/$token'
    | '/admin/audit'
    | '/admin/cron'
    | '/admin/policies'
    | '/admin/settings'
    | '/admin/users'
    | '/documents/$docId'
    | '/documents/new'
    | '/projects/$projectId'
    | '/ships/$shipId'
    | '/contacts/'
    | '/documents/'
    | '/projects/'
    | '/ships/'
    | '/admin/users/groups'
    | '/drive/sheet/$entryId'
    | '/projects/$projectId/files'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/procurements'
    | '/admin/users/'
    | '/projects/$projectId/'
    | '/projects/$projectId/from/$shipId'
    | '/projects/$projectId/issues/$issueId'
    | '/projects/$projectId/procurements/$procurementId'
    | '/projects/$projectId/issues/$issueId/full'
    | '/projects/$projectId/procurements/$procurementId/full'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/denied'
    | '/error'
    | '/login'
    | '/totp-verify'
    | '/admin'
    | '/drive'
    | '/overview'
    | '/shared/$token'
    | '/admin/audit'
    | '/admin/cron'
    | '/admin/policies'
    | '/admin/settings'
    | '/documents/$docId'
    | '/documents/new'
    | '/ships/$shipId'
    | '/contacts'
    | '/documents'
    | '/projects'
    | '/ships'
    | '/admin/users/groups'
    | '/drive/sheet/$entryId'
    | '/projects/$projectId/files'
    | '/projects/$projectId/issues'
    | '/projects/$projectId/procurements'
    | '/admin/users'
    | '/projects/$projectId'
    | '/projects/$projectId/from/$shipId'
    | '/projects/$projectId/issues/$issueId'
    | '/projects/$projectId/procurements/$procurementId'
    | '/projects/$projectId/issues/$issueId/full'
    | '/projects/$projectId/procurements/$procurementId/full'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/denied'
    | '/error'
    | '/login'
    | '/totp-verify'
    | '/_app/admin'
    | '/_app/documents'
    | '/_app/drive'
    | '/_app/overview'
    | '/shared/$token'
    | '/_app/admin/audit'
    | '/_app/admin/cron'
    | '/_app/admin/policies'
    | '/_app/admin/settings'
    | '/_app/admin/users'
    | '/_app/documents/$docId'
    | '/_app/documents/new'
    | '/_app/projects/$projectId'
    | '/_app/ships/$shipId'
    | '/_app/contacts/'
    | '/_app/documents/'
    | '/_app/projects/'
    | '/_app/ships/'
    | '/_app/admin/users/groups'
    | '/_app/drive_/sheet/$entryId'
    | '/_app/projects/$projectId/files'
    | '/_app/projects/$projectId/issues'
    | '/_app/projects/$projectId/procurements'
    | '/_app/admin/users/'
    | '/_app/projects/$projectId/'
    | '/_app/projects/$projectId/from/$shipId'
    | '/_app/projects/$projectId/issues/$issueId'
    | '/_app/projects/$projectId/procurements/$procurementId'
    | '/_app/projects/$projectId_/issues/$issueId/full'
    | '/_app/projects/$projectId_/procurements/$procurementId/full'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DeniedRoute: typeof DeniedRoute
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  TotpVerifyRoute: typeof TotpVerifyRoute
  SharedTokenRoute: typeof SharedTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/totp-verify': {
      id: '/totp-verify'
      path: '/totp-verify'
      fullPath: '/totp-verify'
      preLoaderRoute: typeof TotpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/denied': {
      id: '/denied'
      path: '/denied'
      fullPath: '/denied'
      preLoaderRoute: typeof DeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token': {
      id: '/shared/$token'
      path: '/shared/$token'
      fullPath: '/shared/$token'
      preLoaderRoute: typeof SharedTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/drive': {
      id: '/_app/drive'
      path: '/drive'
      fullPath: '/drive'
      preLoaderRoute: typeof AppDriveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents': {
      id: '/_app/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ships/': {
      id: '/_app/ships/'
      path: '/ships'
      fullPath: '/ships/'
      preLoaderRoute: typeof AppShipsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/': {
      id: '/_app/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof AppDocumentsIndexRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ships/$shipId': {
      id: '/_app/ships/$shipId'
      path: '/ships/$shipId'
      fullPath: '/ships/$shipId'
      preLoaderRoute: typeof AppShipsShipIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/documents/new': {
      id: '/_app/documents/new'
      path: '/new'
      fullPath: '/documents/new'
      preLoaderRoute: typeof AppDocumentsNewRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/documents/$docId': {
      id: '/_app/documents/$docId'
      path: '/$docId'
      fullPath: '/documents/$docId'
      preLoaderRoute: typeof AppDocumentsDocIdRouteImport
      parentRoute: typeof AppDocumentsRoute
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/settings': {
      id: '/_app/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/policies': {
      id: '/_app/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AppAdminPoliciesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/cron': {
      id: '/_app/admin/cron'
      path: '/cron'
      fullPath: '/admin/cron'
      preLoaderRoute: typeof AppAdminCronRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/audit': {
      id: '/_app/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AppAdminAuditRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/projects/$projectId/': {
      id: '/_app/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AppProjectsProjectIdIndexRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/projects/$projectId/procurements': {
      id: '/_app/projects/$projectId/procurements'
      path: '/procurements'
      fullPath: '/projects/$projectId/procurements'
      preLoaderRoute: typeof AppProjectsProjectIdProcurementsRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/issues': {
      id: '/_app/projects/$projectId/issues'
      path: '/issues'
      fullPath: '/projects/$projectId/issues'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId/files': {
      id: '/_app/projects/$projectId/files'
      path: '/files'
      fullPath: '/projects/$projectId/files'
      preLoaderRoute: typeof AppProjectsProjectIdFilesRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/drive_/sheet/$entryId': {
      id: '/_app/drive_/sheet/$entryId'
      path: '/drive/sheet/$entryId'
      fullPath: '/drive/sheet/$entryId'
      preLoaderRoute: typeof AppDriveSheetEntryIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users/groups': {
      id: '/_app/admin/users/groups'
      path: '/groups'
      fullPath: '/admin/users/groups'
      preLoaderRoute: typeof AppAdminUsersGroupsRouteImport
      parentRoute: typeof AppAdminUsersRoute
    }
    '/_app/projects/$projectId/procurements/$procurementId': {
      id: '/_app/projects/$projectId/procurements/$procurementId'
      path: '/$procurementId'
      fullPath: '/projects/$projectId/procurements/$procurementId'
      preLoaderRoute: typeof AppProjectsProjectIdProcurementsProcurementIdRouteImport
      parentRoute: typeof AppProjectsProjectIdProcurementsRoute
    }
    '/_app/projects/$projectId/issues/$issueId': {
      id: '/_app/projects/$projectId/issues/$issueId'
      path: '/$issueId'
      fullPath: '/projects/$projectId/issues/$issueId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdRouteImport
      parentRoute: typeof AppProjectsProjectIdIssuesRoute
    }
    '/_app/projects/$projectId/from/$shipId': {
      id: '/_app/projects/$projectId/from/$shipId'
      path: '/from/$shipId'
      fullPath: '/projects/$projectId/from/$shipId'
      preLoaderRoute: typeof AppProjectsProjectIdFromShipIdRouteImport
      parentRoute: typeof AppProjectsProjectIdRoute
    }
    '/_app/projects/$projectId_/procurements/$procurementId/full': {
      id: '/_app/projects/$projectId_/procurements/$procurementId/full'
      path: '/projects/$projectId/procurements/$procurementId/full'
      fullPath: '/projects/$projectId/procurements/$procurementId/full'
      preLoaderRoute: typeof AppProjectsProjectIdProcurementsProcurementIdFullRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId/full': {
      id: '/_app/projects/$projectId_/issues/$issueId/full'
      path: '/projects/$projectId/issues/$issueId/full'
      fullPath: '/projects/$projectId/issues/$issueId/full'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdFullRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAdminUsersRouteChildren {
  AppAdminUsersGroupsRoute: typeof AppAdminUsersGroupsRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppAdminUsersRouteChildren: AppAdminUsersRouteChildren = {
  AppAdminUsersGroupsRoute: AppAdminUsersGroupsRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppAdminUsersRouteWithChildren = AppAdminUsersRoute._addFileChildren(
  AppAdminUsersRouteChildren,
)

interface AppAdminRouteChildren {
  AppAdminAuditRoute: typeof AppAdminAuditRoute
  AppAdminCronRoute: typeof AppAdminCronRoute
  AppAdminPoliciesRoute: typeof AppAdminPoliciesRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRouteWithChildren
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAuditRoute: AppAdminAuditRoute,
  AppAdminCronRoute: AppAdminCronRoute,
  AppAdminPoliciesRoute: AppAdminPoliciesRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRouteWithChildren,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppDocumentsRouteChildren {
  AppDocumentsDocIdRoute: typeof AppDocumentsDocIdRoute
  AppDocumentsNewRoute: typeof AppDocumentsNewRoute
  AppDocumentsIndexRoute: typeof AppDocumentsIndexRoute
}

const AppDocumentsRouteChildren: AppDocumentsRouteChildren = {
  AppDocumentsDocIdRoute: AppDocumentsDocIdRoute,
  AppDocumentsNewRoute: AppDocumentsNewRoute,
  AppDocumentsIndexRoute: AppDocumentsIndexRoute,
}

const AppDocumentsRouteWithChildren = AppDocumentsRoute._addFileChildren(
  AppDocumentsRouteChildren,
)

interface AppProjectsProjectIdIssuesRouteChildren {
  AppProjectsProjectIdIssuesIssueIdRoute: typeof AppProjectsProjectIdIssuesIssueIdRoute
}

const AppProjectsProjectIdIssuesRouteChildren: AppProjectsProjectIdIssuesRouteChildren =
  {
    AppProjectsProjectIdIssuesIssueIdRoute:
      AppProjectsProjectIdIssuesIssueIdRoute,
  }

const AppProjectsProjectIdIssuesRouteWithChildren =
  AppProjectsProjectIdIssuesRoute._addFileChildren(
    AppProjectsProjectIdIssuesRouteChildren,
  )

interface AppProjectsProjectIdProcurementsRouteChildren {
  AppProjectsProjectIdProcurementsProcurementIdRoute: typeof AppProjectsProjectIdProcurementsProcurementIdRoute
}

const AppProjectsProjectIdProcurementsRouteChildren: AppProjectsProjectIdProcurementsRouteChildren =
  {
    AppProjectsProjectIdProcurementsProcurementIdRoute:
      AppProjectsProjectIdProcurementsProcurementIdRoute,
  }

const AppProjectsProjectIdProcurementsRouteWithChildren =
  AppProjectsProjectIdProcurementsRoute._addFileChildren(
    AppProjectsProjectIdProcurementsRouteChildren,
  )

interface AppProjectsProjectIdRouteChildren {
  AppProjectsProjectIdFilesRoute: typeof AppProjectsProjectIdFilesRoute
  AppProjectsProjectIdIssuesRoute: typeof AppProjectsProjectIdIssuesRouteWithChildren
  AppProjectsProjectIdProcurementsRoute: typeof AppProjectsProjectIdProcurementsRouteWithChildren
  AppProjectsProjectIdIndexRoute: typeof AppProjectsProjectIdIndexRoute
  AppProjectsProjectIdFromShipIdRoute: typeof AppProjectsProjectIdFromShipIdRoute
}

const AppProjectsProjectIdRouteChildren: AppProjectsProjectIdRouteChildren = {
  AppProjectsProjectIdFilesRoute: AppProjectsProjectIdFilesRoute,
  AppProjectsProjectIdIssuesRoute: AppProjectsProjectIdIssuesRouteWithChildren,
  AppProjectsProjectIdProcurementsRoute:
    AppProjectsProjectIdProcurementsRouteWithChildren,
  AppProjectsProjectIdIndexRoute: AppProjectsProjectIdIndexRoute,
  AppProjectsProjectIdFromShipIdRoute: AppProjectsProjectIdFromShipIdRoute,
}

const AppProjectsProjectIdRouteWithChildren =
  AppProjectsProjectIdRoute._addFileChildren(AppProjectsProjectIdRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDocumentsRoute: typeof AppDocumentsRouteWithChildren
  AppDriveRoute: typeof AppDriveRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRouteWithChildren
  AppShipsShipIdRoute: typeof AppShipsShipIdRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppShipsIndexRoute: typeof AppShipsIndexRoute
  AppDriveSheetEntryIdRoute: typeof AppDriveSheetEntryIdRoute
  AppProjectsProjectIdIssuesIssueIdFullRoute: typeof AppProjectsProjectIdIssuesIssueIdFullRoute
  AppProjectsProjectIdProcurementsProcurementIdFullRoute: typeof AppProjectsProjectIdProcurementsProcurementIdFullRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDocumentsRoute: AppDocumentsRouteWithChildren,
  AppDriveRoute: AppDriveRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRouteWithChildren,
  AppShipsShipIdRoute: AppShipsShipIdRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppShipsIndexRoute: AppShipsIndexRoute,
  AppDriveSheetEntryIdRoute: AppDriveSheetEntryIdRoute,
  AppProjectsProjectIdIssuesIssueIdFullRoute:
    AppProjectsProjectIdIssuesIssueIdFullRoute,
  AppProjectsProjectIdProcurementsProcurementIdFullRoute:
    AppProjectsProjectIdProcurementsProcurementIdFullRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DeniedRoute: DeniedRoute,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  TotpVerifyRoute: TotpVerifyRoute,
  SharedTokenRoute: SharedTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
