import type { Config } from "@/config";
import type { AppDatabase } from "@/db";
import type { AppEnv } from "@/shared/lib/types";
import { existsSync, mkdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { count, eq, sql } from "drizzle-orm";
import { Hono } from "hono";
import { customAlphabet } from "nanoid";
import { createDb } from "@/db";
import { users } from "@/modules/account/users/schema";
import { fileReferences, files } from "@/modules/file/schema";
import { __setLocalDriverRootForTests } from "@/modules/file/storage/local";
import { __resetDriverRegistryForTests, setActiveDriver } from "@/modules/file/storage/registry";
import { policyMiddleware } from "@/modules/policy";
import { loadNamespaces } from "@/modules/policy/namespace-config";
import { listRoles } from "@/modules/project/project.roles";
import { addMember, createProject } from "@/modules/project/project.service";
import { driveRoutes } from "./drive.routes";
import {
  createDriveFolder,
  deleteDriveEntryPermanently,
  listDriveEntries,
  restoreDriveEntry,
  trashDriveEntry,
  updateDriveEntry,
  uploadDriveFile,
} from "./drive.service";
import { addTeamMember, createTeamDirectory } from "./drive.team-directory.service";
import { driveEntries } from "./schema";

const nanoid = customAlphabet("0123456789abcdefghijklmnopqrstuvwxyz", 8);

let db: AppDatabase;
let dbPath: string;
let storageRoot: string;

type DriveTestConfig = Pick<Config, "MAX_UPLOAD_BYTES" | "MAX_ATTACHMENTS_PER_RESOURCE" | "UPLOADS_TOTAL_BYTES" | "FILE_GC_MODE" | "FILE_PRESIGN_ENABLED" | "FILE_PRESIGN_TTL_SECONDS">;

const config: DriveTestConfig = {
  MAX_UPLOAD_BYTES: 10 * 1024 * 1024,
  MAX_ATTACHMENTS_PER_RESOURCE: 20,
  UPLOADS_TOTAL_BYTES: 0,
  FILE_GC_MODE: "sync",
  FILE_PRESIGN_ENABLED: false,
  FILE_PRESIGN_TTL_SECONDS: 300,
};

// The Drizzle migration for `projects` / `project_members` is generated by the
// coordinator; build the tables directly so the project owner branch is
// testable in isolation.
const PROJECT_TABLE_DDL: readonly string[] = [
  `CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    short_id TEXT NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    description TEXT,
    start_date TEXT,
    end_date TEXT,
    creator_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    version INTEGER NOT NULL DEFAULT 1,
    deleted_at TEXT,
    updated_at TEXT NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS projects_short_id_idx ON projects (short_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS projects_code_idx ON projects (code)`,
  `CREATE TABLE IF NOT EXISTS project_members (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    member_type TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'member',
    user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    display_name TEXT,
    external_ref TEXT,
    supplier_info TEXT,
    can_view_procurement INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS project_members_project_user_idx ON project_members (project_id, user_id)`,
];

function ensureProjectTables(database: AppDatabase): void {
  for (const ddl of PROJECT_TABLE_DDL)
    database.run(sql.raw(ddl));
}

async function seedUser(name = "Alice") {
  const id = nanoid();
  const now = new Date().toISOString();
  await db.insert(users).values({
    id,
    oauthSub: `sub-${id}`,
    username: `${name.toLowerCase()}-${id}`,
    name,
    email: `${id}@test.com`,
    role: "user",
    status: "active",
    createdAt: now,
    updatedAt: now,
  }).run();
  return id;
}

function textFile(name: string, body = "hello"): File {
  return new File([body], name, { type: "text/plain" });
}

beforeEach(async () => {
  const dir = resolve(tmpdir(), `test-drive-${Date.now()}-${nanoid()}`);
  mkdirSync(dir, { recursive: true });
  dbPath = resolve(dir, "test.db");
  storageRoot = resolve(dir, "blobs");
  db = await createDb(dbPath);
  __resetDriverRegistryForTests();
  __setLocalDriverRootForTests(storageRoot);
  setActiveDriver("local");
  loadNamespaces();
  ensureProjectTables(db);
});

afterEach(() => {
  db.close();
  const dir = resolve(dbPath, "..");
  if (existsSync(dir))
    rmSync(dir, { recursive: true, force: true });
});

function personal(userId: string) {
  return { ownerType: "user" as const, ownerId: userId };
}

describe("drive folders", () => {
  test("creates and lists root folders", async () => {
    const userId = await seedUser();
    const folder = await createDriveFolder(db, {
      ...personal(userId),
      createdBy: userId,
      name: "Projects",
    });

    expect(folder.id).toHaveLength(8);
    expect(folder.type).toBe("folder");
    expect(folder.parentEntryId).toBeNull();

    const entries = await listDriveEntries(db, { ...personal(userId) });
    expect(entries.map(entry => entry.name)).toEqual(["Projects"]);
  });

  test("rejects duplicate names in the same folder", async () => {
    const userId = await seedUser();
    await createDriveFolder(db, { ...personal(userId), createdBy: userId, name: "Projects" });
    await expect(createDriveFolder(db, {
      ...personal(userId),
      createdBy: userId,
      name: "Projects",
    })).rejects.toThrow(/already exists/i);
  });

  test("prevents moving a folder into its descendant", async () => {
    const userId = await seedUser();
    const parent = await createDriveFolder(db, { ...personal(userId), createdBy: userId, name: "Parent" });
    const child = await createDriveFolder(db, {
      ...personal(userId),
      createdBy: userId,
      parentEntryId: parent.id,
      name: "Child",
    });

    await expect(updateDriveEntry(db, {
      ...personal(userId),
      id: parent.id,
      parentEntryId: child.id,
    })).rejects.toThrow(/descendant/i);
  });
});

describe("drive files", () => {
  test("uploads a file entry and releases its blob on permanent delete", async () => {
    const userId = await seedUser();
    const entry = await uploadDriveFile(db, config, {
      ...personal(userId),
      createdBy: userId,
      file: textFile("note.txt", "body"),
    });

    expect(entry.type).toBe("file");
    expect(entry.file?.filename).toBe("note.txt");
    expect(entry.file?.size).toBe(4);

    await deleteDriveEntryPermanently(db, config, personal(userId), entry.id);

    const entryCount = await db.select({ value: count() }).from(driveEntries).get();
    const refCount = await db.select({ value: count() }).from(fileReferences).get();
    const fileCount = await db.select({ value: count() }).from(files).get();
    expect(entryCount?.value).toBe(0);
    expect(refCount?.value).toBe(0);
    expect(fileCount?.value).toBe(0);
  });

  test("trashes folder trees recursively", async () => {
    const userId = await seedUser();
    const folder = await createDriveFolder(db, { ...personal(userId), createdBy: userId, name: "Folder" });
    await uploadDriveFile(db, config, {
      ...personal(userId),
      createdBy: userId,
      parentEntryId: folder.id,
      file: textFile("child.txt"),
    });

    await trashDriveEntry(db, personal(userId), folder.id);

    const normal = await listDriveEntries(db, { ...personal(userId) });
    const trash = await listDriveEntries(db, { ...personal(userId), status: "trash" });
    expect(normal).toHaveLength(0);
    expect(trash).toHaveLength(1);
    expect(trash[0]?.name).toBe("Folder");
  });

  test("restore rolls back when moving out of a trashed parent would duplicate a root name", async () => {
    const userId = await seedUser();
    await createDriveFolder(db, { ...personal(userId), createdBy: userId, name: "Child" });
    const parent = await createDriveFolder(db, { ...personal(userId), createdBy: userId, name: "Parent" });
    const child = await createDriveFolder(db, {
      ...personal(userId),
      createdBy: userId,
      parentEntryId: parent.id,
      name: "Child",
    });
    await trashDriveEntry(db, personal(userId), parent.id);

    await expect(restoreDriveEntry(db, personal(userId), child.id)).rejects.toThrow(/already exists/i);

    const trashRoot = await listDriveEntries(db, { ...personal(userId), status: "trash" });
    expect(trashRoot.map(entry => entry.name)).toEqual(["Parent"]);
    const normalRoot = await listDriveEntries(db, { ...personal(userId) });
    expect(normalRoot.map(entry => entry.name)).toEqual(["Child"]);
  });
});

describe("drive routes owner scope", () => {
  // Pre-set `user` from an `x-uid` header so the route's `authRequired` and
  // the global `policyMiddleware` both short-circuit on `c.get("user")` —
  // this avoids mutating the process-global auth provider (which would leak
  // into other test files).
  function buildApp() {
    const noopLogger = { error() {}, warn() {}, info() {}, debug() {} } as unknown as AppEnv["Variables"]["logger"];
    const app = new Hono<AppEnv>();
    app.use("*", async (c, next) => {
      c.set("db", db);
      c.set("config", config as unknown as AppEnv["Variables"]["config"]);
      c.set("logger", noopLogger);
      c.set("requestId", "t");
      const uid = c.req.header("x-uid");
      if (uid) {
        const u = await db.select().from(users).where(eq(users.id, uid)).get();
        if (u)
          c.set("user", u);
      }
      await next();
    });
    app.use("*", policyMiddleware({ basePath: "" }));
    app.route("/", driveRoutes());
    app.onError((err, c) => {
      const status = (err as { statusCode?: number }).statusCode ?? 500;
      return c.json({ success: false }, status as 400);
    });
    return app;
  }

  test("a directory member can list the directory's entries; a non-member is denied", async () => {
    const ownerId = await seedUser("Owner");
    const memberId = await seedUser("Member");
    const strangerId = await seedUser("Stranger");

    const dir = await createTeamDirectory(db, { name: "Team", createdBy: ownerId });
    await addTeamMember(db, dir.id, ownerId, { userId: memberId, role: "viewer" });
    await createDriveFolder(db, {
      ownerType: "team_directory",
      ownerId: dir.id,
      createdBy: ownerId,
      name: "Shared",
    });

    const app = buildApp();
    const path = `/drive/entries?ownerType=team_directory&ownerId=${dir.id}`;

    const memberRes = await app.request(path, { headers: { "x-uid": memberId } });
    expect(memberRes.status).toBe(200);
    expect((await memberRes.json()).data.map((e: { name: string }) => e.name)).toEqual(["Shared"]);

    const strangerRes = await app.request(path, { headers: { "x-uid": strangerId } });
    expect(strangerRes.status).toBe(403);
  });

  test("ownerType=user ignores a foreign ownerId and stays scoped to the caller", async () => {
    const callerId = await seedUser("Caller");
    const otherId = await seedUser("Other");

    await createDriveFolder(db, { ...personal(callerId), createdBy: callerId, name: "Mine" });
    const app = buildApp();

    const own = await app.request("/drive/entries", { headers: { "x-uid": callerId } });
    expect(own.status).toBe(200);
    expect((await own.json()).data.map((e: { name: string }) => e.name)).toEqual(["Mine"]);

    const foreign = await app.request(`/drive/entries?ownerId=${otherId}`, { headers: { "x-uid": callerId } });
    expect(foreign.status).toBe(403);
  });

  test("searches the selected owner without leaking another drive", async () => {
    const callerId = await seedUser("Caller");
    const otherId = await seedUser("Other");

    await uploadDriveFile(db, config, { ...personal(callerId), createdBy: callerId, file: textFile("report.txt") });
    await uploadDriveFile(db, config, { ...personal(otherId), createdBy: otherId, file: textFile("report-secret.txt") });

    const app = buildApp();
    const own = await app.request("/drive/entries/search?q=report", { headers: { "x-uid": callerId } });
    expect(own.status).toBe(200);
    expect((await own.json()).data.map((e: { name: string }) => e.name)).toEqual(["report.txt"]);

    const foreign = await app.request(`/drive/entries/search?q=report&ownerType=user&ownerId=${otherId}`, { headers: { "x-uid": callerId } });
    expect(foreign.status).toBe(403);
  });

  test("editor creates a folder in a team directory; viewer and non-member are denied", async () => {
    const ownerId = await seedUser("Owner");
    const editorId = await seedUser("Editor");
    const viewerId = await seedUser("Viewer");
    const strangerId = await seedUser("Stranger");

    const dir = await createTeamDirectory(db, { name: "Team", createdBy: ownerId });
    await addTeamMember(db, dir.id, ownerId, { userId: editorId, role: "editor" });
    await addTeamMember(db, dir.id, ownerId, { userId: viewerId, role: "viewer" });

    const app = buildApp();
    const post = (uid: string, name: string) => app.request("/drive/folders", {
      method: "POST",
      headers: { "x-uid": uid, "content-type": "application/json" },
      body: JSON.stringify({ name, ownerType: "team_directory", ownerId: dir.id }),
    });

    const byEditor = await post(editorId, "EditorFolder");
    expect(byEditor.status).toBe(201);
    const created = (await byEditor.json()).data;
    expect(created.ownerType).toBe("team_directory");
    expect(created.ownerId).toBe(dir.id);

    expect((await post(viewerId, "ViewerFolder")).status).toBe(403);
    expect((await post(strangerId, "StrangerFolder")).status).toBe(403);
  });

  test("editor creates a text-file in a team directory; viewer is denied", async () => {
    const ownerId = await seedUser("Owner");
    const editorId = await seedUser("Editor");
    const viewerId = await seedUser("Viewer");

    const dir = await createTeamDirectory(db, { name: "Team", createdBy: ownerId });
    await addTeamMember(db, dir.id, ownerId, { userId: editorId, role: "editor" });
    await addTeamMember(db, dir.id, ownerId, { userId: viewerId, role: "viewer" });

    const app = buildApp();
    const post = (uid: string, name: string) => app.request("/drive/entries/text-file", {
      method: "POST",
      headers: { "x-uid": uid, "content-type": "application/json" },
      body: JSON.stringify({ name, content: "hello", ownerType: "team_directory", ownerId: dir.id }),
    });

    const byEditor = await post(editorId, "note.txt");
    expect(byEditor.status).toBe(201);
    expect((await byEditor.json()).data.ownerId).toBe(dir.id);

    expect((await post(viewerId, "viewer.txt")).status).toBe(403);
  });

  test("folder/text-file creation with ownerType=user stays caller-scoped", async () => {
    const callerId = await seedUser("Caller");
    const otherId = await seedUser("Other");
    const app = buildApp();

    const ownFolder = await app.request("/drive/folders", {
      method: "POST",
      headers: { "x-uid": callerId, "content-type": "application/json" },
      body: JSON.stringify({ name: "Mine" }),
    });
    expect(ownFolder.status).toBe(201);
    const folder = (await ownFolder.json()).data;
    expect(folder.ownerType).toBe("user");
    expect(folder.ownerId).toBe(callerId);

    const foreign = await app.request("/drive/folders", {
      method: "POST",
      headers: { "x-uid": callerId, "content-type": "application/json" },
      body: JSON.stringify({ name: "Sneaky", ownerType: "user", ownerId: otherId }),
    });
    expect(foreign.status).toBe(403);
  });

  test("a project member can create/list project entries; a non-member is denied", async () => {
    const pmId = await seedUser("PM");
    const strangerId = await seedUser("Stranger");
    const project = await createProject(db, { name: "Bridge", creatorId: pmId });

    const app = buildApp();

    const created = await app.request("/drive/folders", {
      method: "POST",
      headers: { "x-uid": pmId, "content-type": "application/json" },
      body: JSON.stringify({ name: "Sub", ownerType: "project", ownerId: project.shortId }),
    });
    expect(created.status).toBe(201);
    // The client addresses the project by shortId; entries store the internal ULID.
    expect((await created.json()).data.ownerId).toBe(project.id);

    const listPath = `/drive/entries?ownerType=project&ownerId=${project.shortId}`;
    expect((await app.request(listPath, { headers: { "x-uid": pmId } })).status).toBe(200);
    expect((await app.request(listPath, { headers: { "x-uid": strangerId } })).status).toBe(403);
  });

  test("Reader (files.view) can list project files but cannot create", async () => {
    const ownerId = await seedUser("Owner");
    const readerId = await seedUser("Reader");
    const project = await createProject(db, { name: "ReadOnly", creatorId: ownerId });
    const roles = await listRoles(db, project.id);
    const readerRoleId = roles.find(r => r.name === "Reader")!.id;
    await addMember(db, project.id, { roleId: readerRoleId, userId: readerId });

    const app = buildApp();
    const listPath = `/drive/entries?ownerType=project&ownerId=${project.shortId}`;

    expect((await app.request(listPath, { headers: { "x-uid": readerId } })).status).toBe(200);

    const createRes = await app.request("/drive/folders", {
      method: "POST",
      headers: { "x-uid": readerId, "content-type": "application/json" },
      body: JSON.stringify({ name: "Forbidden", ownerType: "project", ownerId: project.shortId }),
    });
    expect(createRes.status).toBe(403);
  });

  test("Guest (no capabilities) cannot list project files", async () => {
    const ownerId = await seedUser("Owner");
    const guestId = await seedUser("Guest");
    const project = await createProject(db, { name: "GuestProject", creatorId: ownerId });
    const roles = await listRoles(db, project.id);
    const guestRoleId = roles.find(r => r.name === "Guest")!.id;
    await addMember(db, project.id, { roleId: guestRoleId, userId: guestId });

    const app = buildApp();
    const listPath = `/drive/entries?ownerType=project&ownerId=${project.shortId}`;

    expect((await app.request(listPath, { headers: { "x-uid": guestId } })).status).toBe(403);
  });

  test("Writer (files.manage) can create project files", async () => {
    const ownerId = await seedUser("Owner");
    const writerId = await seedUser("Writer");
    const project = await createProject(db, { name: "WriteProject", creatorId: ownerId });
    const roles = await listRoles(db, project.id);
    const writerRoleId = roles.find(r => r.name === "Writer")!.id;
    await addMember(db, project.id, { roleId: writerRoleId, userId: writerId });

    const app = buildApp();
    const createRes = await app.request("/drive/folders", {
      method: "POST",
      headers: { "x-uid": writerId, "content-type": "application/json" },
      body: JSON.stringify({ name: "WriterFolder", ownerType: "project", ownerId: project.shortId }),
    });
    expect(createRes.status).toBe(201);
  });

  test("personal and team-directory paths are unaffected by project capability gates", async () => {
    const userId = await seedUser("User");
    const editorId = await seedUser("Editor");
    const dir = await createTeamDirectory(db, { name: "Team", createdBy: userId });
    await addTeamMember(db, dir.id, userId, { userId: editorId, role: "editor" });

    const app = buildApp();

    // Personal drive: any authenticated user can list and create their own files
    expect((await app.request("/drive/entries", { headers: { "x-uid": userId } })).status).toBe(200);
    const personalCreate = await app.request("/drive/folders", {
      method: "POST",
      headers: { "x-uid": userId, "content-type": "application/json" },
      body: JSON.stringify({ name: "MyFolder" }),
    });
    expect(personalCreate.status).toBe(201);

    // Team directory: editor can create, viewer is separate concern (already tested above)
    const tdCreate = await app.request("/drive/folders", {
      method: "POST",
      headers: { "x-uid": editorId, "content-type": "application/json" },
      body: JSON.stringify({ name: "TdFolder", ownerType: "team_directory", ownerId: dir.id }),
    });
    expect(tdCreate.status).toBe(201);
  });
});
