import type { AppDatabase } from "@/db";
import { existsSync, mkdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import { afterEach, beforeEach, describe, expect, test } from "bun:test";
import { sql } from "drizzle-orm";
import { customAlphabet } from "nanoid";
import { createDb } from "@/db";
import { users } from "@/modules/account/users/schema";
import {
  addMember,
  canViewProcurement,
  createProject,
  getProjectByShortId,
  getRole,
  isMember,
  listMembers,
  listProjects,
  removeMember,
  resolveAssignableMember,
  resolveProjectId,
  softDeleteProject,
  updateMember,
  updateProject,
} from "./project.service";

const nanoid = customAlphabet("0123456789abcdefghijklmnopqrstuvwxyz", 8);

let db: AppDatabase;
let dbPath: string;

// The Drizzle migration for `projects` / `project_members` is generated by the
// coordinator, so it may not exist when this suite runs. Build the two tables
// directly from the schema definition so the service is testable in isolation.
const PROJECT_TABLE_DDL: readonly string[] = [
  `CREATE TABLE IF NOT EXISTS projects (
    id TEXT PRIMARY KEY,
    short_id TEXT NOT NULL,
    code TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    description TEXT,
    start_date TEXT,
    end_date TEXT,
    creator_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    version INTEGER NOT NULL DEFAULT 1,
    deleted_at TEXT,
    updated_at TEXT NOT NULL
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS projects_short_id_idx ON projects (short_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS projects_code_idx ON projects (code)`,
  `CREATE INDEX IF NOT EXISTS projects_status_idx ON projects (status, deleted_at)`,
  `CREATE TABLE IF NOT EXISTS project_members (
    id TEXT PRIMARY KEY,
    project_id TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    member_type TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'member',
    user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
    display_name TEXT,
    external_ref TEXT,
    supplier_info TEXT,
    can_view_procurement INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE INDEX IF NOT EXISTS project_members_project_idx ON project_members (project_id)`,
  `CREATE INDEX IF NOT EXISTS project_members_user_idx ON project_members (user_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS project_members_project_user_idx ON project_members (project_id, user_id)`,
];

function ensureProjectTables(database: AppDatabase): void {
  for (const ddl of PROJECT_TABLE_DDL)
    database.run(sql.raw(ddl));
}

async function seedUser(name: string): Promise<string> {
  const id = nanoid();
  const now = new Date().toISOString();
  await db.insert(users).values({
    id,
    oauthSub: `sub-${id}`,
    username: `${name.toLowerCase()}-${id}`,
    name,
    email: `${id}@test.com`,
    role: "user",
    status: "active",
    createdAt: now,
    updatedAt: now,
  }).run();
  return id;
}

beforeEach(async () => {
  const dir = resolve(tmpdir(), `test-project-${Date.now()}-${nanoid()}`);
  mkdirSync(dir, { recursive: true });
  dbPath = resolve(dir, "test.db");
  db = await createDb(dbPath);
  ensureProjectTables(db);
});

afterEach(() => {
  db.close();
  const dir = resolve(dbPath, "..");
  if (existsSync(dir))
    rmSync(dir, { recursive: true, force: true });
});

describe("createProject", () => {
  test("writes the project row and the creator as a pm internal member", async () => {
    const creator = await seedUser("Alice");
    const project = await createProject(db, { name: "Bridge", creatorId: creator });

    expect(project.shortId).toHaveLength(8);
    expect(project.name).toBe("Bridge");
    expect(project.status).toBe("active");
    expect(project.version).toBe(1);
    expect(project.code).toContain("P-");

    const members = await listMembers(db, project.id);
    expect(members).toHaveLength(1);
    expect(members[0]!.userId).toBe(creator);
    expect(members[0]!.role).toBe("pm");
    expect(members[0]!.memberType).toBe("internal");
    expect(members[0]!.canViewProcurement).toBe(1);
  });

  test("accepts a provided code", async () => {
    const creator = await seedUser("Alice");
    const project = await createProject(db, { name: "Tower", code: "TOWER-1", creatorId: creator });
    expect(project.code).toBe("TOWER-1");
  });
});

describe("members", () => {
  test("adds an internal and an external member", async () => {
    const creator = await seedUser("Alice");
    const bob = await seedUser("Bob");
    const project = await createProject(db, { name: "P", creatorId: creator });

    const internal = await addMember(db, project.id, { memberType: "internal", userId: bob });
    expect(internal.userId).toBe(bob);
    expect(internal.role).toBe("member");

    const external = await addMember(db, project.id, {
      memberType: "external",
      displayName: "Supplier Co",
      externalRef: "ext-1",
    });
    expect(external.userId).toBeNull();
    expect(external.displayName).toBe("Supplier Co");

    const members = await listMembers(db, project.id);
    expect(members).toHaveLength(3); // creator + 2
  });

  test("promotes an external member to internal", async () => {
    const creator = await seedUser("Alice");
    const carol = await seedUser("Carol");
    const project = await createProject(db, { name: "P", creatorId: creator });

    const external = await addMember(db, project.id, { memberType: "external", displayName: "Ext" });
    const promoted = await updateMember(db, project.id, external.id, { userId: carol });
    expect(promoted?.memberType).toBe("internal");
    expect(promoted?.userId).toBe(carol);
  });

  test("removeMember deletes the row", async () => {
    const creator = await seedUser("Alice");
    const bob = await seedUser("Bob");
    const project = await createProject(db, { name: "P", creatorId: creator });
    const member = await addMember(db, project.id, { memberType: "internal", userId: bob });

    expect(await removeMember(db, project.id, member.id)).toBe(true);
    expect(await removeMember(db, project.id, member.id)).toBe(false);
  });
});

describe("updateProject", () => {
  test("bumps version and applies the patch", async () => {
    const creator = await seedUser("Alice");
    const project = await createProject(db, { name: "P", creatorId: creator });
    const updated = await updateProject(db, project.shortId, { name: "P2", status: "archived" });
    expect(updated?.name).toBe("P2");
    expect(updated?.status).toBe("archived");
    expect(updated!.version).toBe(2);
  });
});

describe("softDeleteProject", () => {
  test("hides the project from reads but keeps member rows", async () => {
    const creator = await seedUser("Alice");
    const project = await createProject(db, { name: "P", creatorId: creator });
    await softDeleteProject(db, project.shortId);

    expect(await getProjectByShortId(db, project.shortId)).toBeUndefined();
    expect(await resolveProjectId(db, project.shortId)).toBeNull();
    // member rows survive a soft delete (no hard delete → no cascade)
    expect(await listMembers(db, project.id)).toHaveLength(1);
  });
});

describe("listProjects", () => {
  test("paginates, filters by status, excludes soft-deleted", async () => {
    const creator = await seedUser("Alice");
    await createProject(db, { name: "A", status: "active", creatorId: creator });
    await createProject(db, { name: "B", status: "archived", creatorId: creator });
    const deleted = await createProject(db, { name: "C", creatorId: creator });
    await softDeleteProject(db, deleted.shortId);

    const all = await listProjects(db, {});
    expect(all.total).toBe(2);

    const archived = await listProjects(db, { status: "archived" });
    expect(archived.total).toBe(1);
    expect(archived.data[0]!.name).toBe("B");
  });

  test("memberUserId scopes the list to the caller's projects", async () => {
    const owner = await seedUser("Owner");
    const outsider = await seedUser("Outsider");
    await createProject(db, { name: "Owned", creatorId: owner });

    // The creator is a pm member, so sees it; the outsider is not a member.
    const mine = await listProjects(db, { memberUserId: owner });
    expect(mine.total).toBe(1);
    const theirs = await listProjects(db, { memberUserId: outsider });
    expect(theirs.total).toBe(0);
  });
});

describe("access helpers", () => {
  test("isMember / getRole reflect membership and fail-closed for non-members", async () => {
    const creator = await seedUser("Alice");
    const bob = await seedUser("Bob");
    const outsider = await seedUser("Eve");
    const project = await createProject(db, { name: "P", creatorId: creator });
    await addMember(db, project.id, { memberType: "internal", userId: bob, role: "member" });

    expect(await isMember(db, project.id, creator)).toBe(true);
    expect(await isMember(db, project.id, bob)).toBe(true);
    expect(await isMember(db, project.id, outsider)).toBe(false);

    expect(await getRole(db, project.id, creator)).toBe("pm");
    expect(await getRole(db, project.id, bob)).toBe("member");
    expect(await getRole(db, project.id, outsider)).toBeNull();
  });

  test("canViewProcurement is true for pm or members flagged for it", async () => {
    const creator = await seedUser("Alice");
    const bob = await seedUser("Bob");
    const carol = await seedUser("Carol");
    const outsider = await seedUser("Eve");
    const project = await createProject(db, { name: "P", creatorId: creator });
    await addMember(db, project.id, { memberType: "internal", userId: bob });
    await addMember(db, project.id, { memberType: "internal", userId: carol, canViewProcurement: true });

    expect(await canViewProcurement(db, project.id, creator)).toBe(true); // pm
    expect(await canViewProcurement(db, project.id, bob)).toBe(false);
    expect(await canViewProcurement(db, project.id, carol)).toBe(true);
    expect(await canViewProcurement(db, project.id, outsider)).toBe(false);
  });

  test("resolveAssignableMember validates ownership", async () => {
    const creator = await seedUser("Alice");
    const bob = await seedUser("Bob");
    const projectA = await createProject(db, { name: "A", creatorId: creator });
    const projectB = await createProject(db, { name: "B", creatorId: creator });
    const member = await addMember(db, projectA.id, { memberType: "internal", userId: bob });

    const resolved = await resolveAssignableMember(db, projectA.id, member.id);
    expect(resolved?.id).toBe(member.id);
    expect(resolved?.memberType).toBe("internal");
    expect(resolved?.userId).toBe(bob);

    // same member id, wrong project → null
    expect(await resolveAssignableMember(db, projectB.id, member.id)).toBeNull();
    expect(await resolveAssignableMember(db, projectA.id, "missing")).toBeNull();
  });
});
