#!/usr/bin/env bun
// Generate apps/web/src/shared/lib/api/_generated/api-types.ts from the
// committed OpenAPI spec (skills/bithk/references/api-spec.json) via
// openapi-typescript. The spec itself is generated from the live Hono routes
// by `bun run gen:api-spec` and drift-gated by `check:api-spec`, so the type
// chain server -> spec -> TS stays drift-free end to end.
//
// Usage:
//   bun scripts/gen-api-types.ts          # write the types
//   bun scripts/gen-api-types.ts --check  # non-zero on drift
/* eslint-disable no-console */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import process from "node:process";
import { parseArgs } from "node:util";
import openapiTS, { astToString } from "openapi-typescript";

const { values: cli } = parseArgs({
  args: process.argv.slice(2),
  options: { check: { type: "boolean", default: false } },
  strict: true,
  allowPositionals: false,
});

const ROOT = resolve(import.meta.dir, "..");
const SPEC_PATH = resolve(ROOT, "skills/bithk/references/api-spec.json");
const OUT_PATH = resolve(ROOT, "apps/web/src/shared/lib/api/_generated/api-types.ts");

const HEADER = `/* eslint-disable */
// Generated by \`bun run gen:api-types\` from skills/bithk/references/api-spec.json
// (itself generated from the live Hono routes by \`bun run gen:api-spec\`).
// Do not edit by hand — regenerate and commit. CI verifies via \`check:api-types\`.
`;

// The spec generator (apps/api/scripts/gen-api-spec.ts) hoists recursive
// schemas' `$defs` into components.schemas, so the committed spec is
// self-contained and can be fed to openapi-typescript as-is.
const spec = JSON.parse(readFileSync(SPEC_PATH, "utf-8")) as Parameters<typeof openapiTS>[0];
const ast = await openapiTS(spec, {
  // Emit readonly properties so the generated views match the repo's
  // immutable-by-default data-layer convention.
  immutable: true,
});
const rendered = `${HEADER}${astToString(ast)}`;

if (cli.check) {
  const existing = (() => {
    try {
      return readFileSync(OUT_PATH, "utf-8");
    }
    catch {
      return "";
    }
  })();
  if (existing.trim() !== rendered.trim()) {
    console.error(`[gen-api-types] ${OUT_PATH} is stale. Run \`bun run gen:api-types\` and commit.`);
    process.exit(1);
  }
  console.log("[gen-api-types] up to date");
}
else {
  writeFileSync(OUT_PATH, rendered);
  console.log(`[gen-api-types] wrote ${OUT_PATH}`);
}
