#!/usr/bin/env bun
// Generate apps/web/src/shared/lib/api/_generated/api-types.ts from the
// committed OpenAPI spec (skills/bithk/references/api-spec.json) via
// openapi-typescript. The spec itself is generated from the live Hono routes
// by `bun run gen:api-spec` and drift-gated by `check:api-spec`, so the type
// chain server -> spec -> TS stays drift-free end to end.
//
// Usage:
//   bun scripts/gen-api-types.ts          # write the types
//   bun scripts/gen-api-types.ts --check  # non-zero on drift
/* eslint-disable no-console */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import process from "node:process";
import { parseArgs } from "node:util";
import openapiTS, { astToString } from "openapi-typescript";

const { values: cli } = parseArgs({
  args: process.argv.slice(2),
  options: { check: { type: "boolean", default: false } },
  strict: true,
  allowPositionals: false,
});

const ROOT = resolve(import.meta.dir, "..");
const SPEC_PATH = resolve(ROOT, "skills/bithk/references/api-spec.json");
const OUT_PATH = resolve(ROOT, "apps/web/src/shared/lib/api/_generated/api-types.ts");

const HEADER = `/* eslint-disable */
// Generated by \`bun run gen:api-types\` from skills/bithk/references/api-spec.json
// (itself generated from the live Hono routes by \`bun run gen:api-spec\`).
// Do not edit by hand — regenerate and commit. CI verifies via \`check:api-types\`.
`;

// hono-openapi emits recursive zod schemas as schema-local `$defs` whose
// `$ref`s point at `#/components/schemas/<name>` — a target it never creates
// (see /policy/expand). Hoist every `$defs` entry into components.schemas so
// those refs resolve; collide loudly rather than silently overwrite.
interface SpecDoc {
  components?: { schemas?: Record<string, unknown> };
  [key: string]: unknown;
}
function hoistLocalDefs(doc: SpecDoc): SpecDoc {
  const schemas: Record<string, unknown> = { ...doc.components?.schemas };
  const visit = (node: unknown): void => {
    if (node === null || typeof node !== "object")
      return;
    if (Array.isArray(node)) {
      node.forEach(visit);
      return;
    }
    const obj = node as Record<string, unknown>;
    const defs = obj.$defs;
    if (defs && typeof defs === "object" && !Array.isArray(defs)) {
      for (const [name, schema] of Object.entries(defs as Record<string, unknown>)) {
        if (name in schemas && JSON.stringify(schemas[name]) !== JSON.stringify(schema))
          throw new Error(`[gen-api-types] conflicting $defs schema "${name}" — cannot hoist`);
        schemas[name] = schema;
      }
      delete obj.$defs;
    }
    Object.values(obj).forEach(visit);
  };
  visit(doc);
  if (Object.keys(schemas).length === 0)
    return doc;
  return { ...doc, components: { ...doc.components, schemas } };
}

const spec = hoistLocalDefs(JSON.parse(readFileSync(SPEC_PATH, "utf-8")) as SpecDoc);
const ast = await openapiTS(spec, {
  // Emit readonly properties so the generated views match the repo's
  // immutable-by-default data-layer convention.
  immutable: true,
});
const rendered = `${HEADER}${astToString(ast)}`;

if (cli.check) {
  const existing = (() => {
    try {
      return readFileSync(OUT_PATH, "utf-8");
    }
    catch {
      return "";
    }
  })();
  if (existing.trim() !== rendered.trim()) {
    console.error(`[gen-api-types] ${OUT_PATH} is stale. Run \`bun run gen:api-types\` and commit.`);
    process.exit(1);
  }
  console.log("[gen-api-types] up to date");
}
else {
  writeFileSync(OUT_PATH, rendered);
  console.log(`[gen-api-types] wrote ${OUT_PATH}`);
}
