#!/usr/bin/env bun
// Generate skills/bithk/references/api-spec.json (OpenAPI 3.1) from the live
// Hono routes. The spec is derived by `hono-openapi` from each route's
// `describeRoute` + `validator` metadata — no hand-authoring, no drift. A route
// without `describeRoute` simply does not appear, so migrating a module adds
// its routes to the spec automatically.
//
// Usage:
//   bun scripts/gen-api-spec.ts          # write the spec
//   bun scripts/gen-api-spec.ts --check  # non-zero on drift
/* eslint-disable no-console */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import process from "node:process";
import { parseArgs } from "node:util";
import { generateSpecs } from "hono-openapi";
import { buildApiApp } from "./lib/route-table";

const { values: cli } = parseArgs({
  args: process.argv.slice(2),
  options: { check: { type: "boolean", default: false } },
  strict: true,
  allowPositionals: false,
});

const ROOT = resolve(import.meta.dir, "..", "..", "..");
const OUT_PATH = resolve(ROOT, "skills/bithk/references/api-spec.json");

// hono-openapi emits recursive zod schemas (e.g. /policy/expand's subject
// node) as schema-local `$defs` whose `$ref`s point at
// `#/components/schemas/<name>` — a target it never creates, leaving the spec
// with dangling refs. Hoist every `$defs` entry into components.schemas so the
// emitted spec is self-contained; collide loudly rather than silently
// overwrite.
interface SpecDoc {
  components?: { schemas?: Record<string, unknown> };
  [key: string]: unknown;
}
function hoistLocalDefs(doc: SpecDoc): SpecDoc {
  const schemas: Record<string, unknown> = { ...doc.components?.schemas };
  const visit = (node: unknown): void => {
    if (node === null || typeof node !== "object")
      return;
    if (Array.isArray(node)) {
      node.forEach(visit);
      return;
    }
    const obj = node as Record<string, unknown>;
    const defs = obj.$defs;
    if (defs && typeof defs === "object" && !Array.isArray(defs)) {
      for (const [name, schema] of Object.entries(defs as Record<string, unknown>)) {
        if (name in schemas && JSON.stringify(schemas[name]) !== JSON.stringify(schema))
          throw new Error(`[gen-api-spec] conflicting $defs schema "${name}" — cannot hoist`);
        schemas[name] = schema;
      }
      delete obj.$defs;
    }
    Object.values(obj).forEach(visit);
  };
  visit(doc);
  if (Object.keys(schemas).length === 0)
    return doc;
  return { ...doc, components: { ...doc.components, schemas } };
}

function appVersion(): string {
  try {
    const pkg = JSON.parse(readFileSync(resolve(ROOT, "package.json"), "utf-8")) as { version?: string };
    return pkg.version ?? "0.0.0";
  }
  catch {
    return "0.0.0";
  }
}

const rawDoc = await generateSpecs(buildApiApp(), {
  documentation: {
    info: {
      title: "bithk API",
      version: appVersion(),
      description:
        "Personal Access Token (`bithk_pat_…`) authenticated REST API. "
        + "Generated by `bun run gen:api-spec` from the live Hono routes "
        + "(hono-openapi); do not edit by hand.",
    },
    servers: [{ url: "/api" }],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: "http",
          scheme: "bearer",
          description:
            "Personal Access Token (`bithk_pat_…`). Effective access is the "
            + "owner's permissions intersected with the token's per-module scope.",
        },
      },
    },
    security: [{ bearerAuth: [] }],
  },
  excludeMethods: ["OPTIONS", "HEAD"],
});
const doc = hoistLocalDefs(rawDoc as SpecDoc);

const rendered = `${JSON.stringify(doc, null, 2)}\n`;
const pathCount = Object.keys((doc as { paths?: Record<string, unknown> }).paths ?? {}).length;

if (cli.check) {
  const existing = (() => {
    try {
      return readFileSync(OUT_PATH, "utf-8");
    }
    catch {
      return "";
    }
  })();
  if (existing.trim() !== rendered.trim()) {
    console.error(`[gen-api-spec] ${OUT_PATH} is stale. Run \`bun run gen:api-spec\` and commit.`);
    process.exit(1);
  }
  console.log(`[gen-api-spec] up to date (${pathCount} documented paths)`);
}
else {
  writeFileSync(OUT_PATH, rendered);
  console.log(`[gen-api-spec] wrote ${OUT_PATH} (${pathCount} documented paths)`);
}
