#!/usr/bin/env bun
// Generate docs/reference/api-routes.md from the in-process Hono routes table.
// Walks each module's `*.routes.ts` factory — no live server, no DB.
//
// Usage:
//   bun scripts/gen-api-docs.ts          # write docs/reference/api-routes.md
//   bun scripts/gen-api-docs.ts --check  # non-zero on drift
/* eslint-disable no-console */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import process from "node:process";
import { parseArgs } from "node:util";
import { collectApiRoutes } from "./lib/route-table";

const { values: cli } = parseArgs({
  args: process.argv.slice(2),
  options: { check: { type: "boolean", default: false } },
  strict: true,
  allowPositionals: false,
});

const ROOT = resolve(import.meta.dir, "..", "..", "..");
const OUT_PATH = resolve(ROOT, "docs/reference/api-routes.md");

interface Row {
  readonly method: string;
  readonly path: string;
}

const rows: Row[] = collectApiRoutes().map(r => ({ method: r.method, path: `/api${r.path}` }));

function render(rs: readonly Row[]): string {
  const header = "# API routes (generated)\n\n"
    + "> Auto-generated by `bun run gen:api-docs` from the in-process Hono\n"
    + "> routes table. The long-form per-module narrative lives in\n"
    + "> [`api.md`](api.md); this file is the flat per-route index that CI\n"
    + "> verifies is up to date.\n\n"
    + `> ${rs.length} routes total.\n\n`
    + "| Method | Path |\n"
    + "|---|---|\n";
  const body = rs.map(r => `| ${r.method} | \`${r.path}\` |`).join("\n");
  return `${header}${body}\n`;
}

const rendered = render(rows);

if (cli.check) {
  const existing = (() => {
    try {
      return readFileSync(OUT_PATH, "utf-8");
    }
    catch {
      return "";
    }
  })();
  if (existing.trim() !== rendered.trim()) {
    console.error(`[gen-api-docs] ${OUT_PATH} is stale. Run \`bun run gen:api-docs\` and commit.`);
    process.exit(1);
  }
  console.log("[gen-api-docs] up to date");
}
else {
  writeFileSync(OUT_PATH, rendered);
  console.log(`[gen-api-docs] wrote ${OUT_PATH} (${rows.length} routes)`);
}
