import type { JsonObject, ModuleSpec, OperationEntry } from "./types";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { collectApiRoutes } from "../lib/route-table";
import { accountSpec } from "./account";
import { auditSpec } from "./audit";
import { backupSpec } from "./backup";
import { COMPONENT_SCHEMAS, SECURITY_SCHEMES } from "./components";
import { contactsSpec } from "./contacts";
import { cronSpec } from "./cron";
import { documentsSpec } from "./documents";
import { driveSpec } from "./drive";
import { filesSpec } from "./files";
import { hrSpec } from "./hr";
import { policySpec } from "./policy";
import { projectsSpec } from "./projects";
import { searchSpec } from "./search";
import { settingsSpec } from "./settings";
import { sharesSpec } from "./shares";
import { shipsSpec } from "./ships";
import { systemSpec } from "./system";
import { tagsSpec } from "./tags";

const MODULE_SPECS: readonly ModuleSpec[] = [
  projectsSpec,
  shipsSpec,
  documentsSpec,
  driveSpec,
  filesSpec,
  contactsSpec,
  hrSpec,
  tagsSpec,
  sharesSpec,
  searchSpec,
  accountSpec,
  settingsSpec,
  policySpec,
  auditSpec,
  backupSpec,
  cronSpec,
  systemSpec,
];

const ROOT = resolve(import.meta.dir, "..", "..", "..", "..");

function appVersion(): string {
  try {
    const pkg = JSON.parse(readFileSync(resolve(ROOT, "package.json"), "utf-8")) as { version?: string };
    return pkg.version ?? "0.0.0";
  }
  catch {
    return "0.0.0";
  }
}

/** `/projects/:projectId` -> `/projects/{projectId}`. */
function toOpenApiPath(path: string): string {
  return path.replace(/:(\w+)/g, "{$1}");
}

function pathParameters(path: string): JsonObject[] {
  return [...path.matchAll(/:(\w+)/g)].map(m => ({
    name: m[1],
    in: "path",
    required: true,
    schema: { type: "string" },
  }));
}

/** Minimal valid operation for a route no module has curated yet. */
function autoStub(method: string, path: string): JsonObject {
  const params = pathParameters(path);
  return {
    "summary": `${method} ${path}`,
    "description": "Auto-generated stub — request/response not yet curated for this route.",
    ...(params.length > 0 ? { parameters: params } : {}),
    "responses": {
      default: {
        description: "Response envelope `{ success, data }` or `{ success, error }`.",
        content: {
          "application/json": {
            schema: { type: "object", properties: { success: { type: "boolean" } } },
          },
        },
      },
    },
    "x-stub": true,
  };
}

export interface BuildResult {
  readonly doc: JsonObject;
  /** Curated `"METHOD /path"` keys that match no real route (typos / removed routes). */
  readonly stale: string[];
  /** Real `"METHOD /path"` routes with no entry in the document (should be empty). */
  readonly uncovered: string[];
  readonly routeCount: number;
  readonly curatedCount: number;
}

export function buildSpec(): BuildResult {
  const routes = collectApiRoutes();
  const routeKeys = new Set(routes.map(r => `${r.method} ${r.path}`));

  const curated = new Map<string, OperationEntry>();
  const schemas: Record<string, JsonObject> = { ...COMPONENT_SCHEMAS };
  for (const spec of MODULE_SPECS) {
    for (const [name, schema] of Object.entries(spec.schemas ?? {}))
      schemas[name] = schema;
    for (const op of spec.operations)
      curated.set(`${op.method} ${op.path}`, op);
  }

  const stale = [...curated.keys()].filter(k => !routeKeys.has(k)).sort();

  const paths: Record<string, JsonObject> = {};
  const uncovered: string[] = [];
  for (const r of routes) {
    const entry = curated.get(`${r.method} ${r.path}`);
    const operation = entry ? entry.operation : autoStub(r.method, r.path);
    const oaPath = toOpenApiPath(r.path);
    const item = (paths[oaPath] ??= {}) as JsonObject;
    item[r.method.toLowerCase()] = operation;
    if (!item[r.method.toLowerCase()])
      uncovered.push(`${r.method} ${r.path}`);
  }

  const doc: JsonObject = {
    openapi: "3.1.0",
    info: {
      title: "bithk API",
      version: appVersion(),
      description:
        "Personal Access Token (`bithk_pat_…`) authenticated REST API. "
        + "Generated by `bun run gen:api-spec`; do not edit by hand. "
        + "Routes marked `x-stub: true` have not had their parameters curated yet.",
    },
    servers: [{ url: "/api" }],
    security: [{ bearerAuth: [] }],
    components: { securitySchemes: SECURITY_SCHEMES, schemas },
    paths,
  };

  return { doc, stale, uncovered, routeCount: routes.length, curatedCount: curated.size };
}
