import type { Config } from "@/config";
import { existsSync, mkdirSync } from "node:fs";
import { dirname, isAbsolute, resolve } from "node:path";
import { ROOT_DIR } from "@/root";
import { getActiveDriver } from "./storage/registry";

// Image preview cache (FEAT-044, Part C). Inline image requests with
// `?thumb=<w>` are served as cached WebP thumbnails generated by Bun's native
// `Bun.Image` — so the file grid stops refetching full-resolution images and a
// remote backend (S3) is hit at most once per (image, width). The cache is
// content-addressed (key = sha256 + width), so entries never need invalidation.

type PreviewCacheConfig = Pick<Config, "FILE_PREVIEW_CACHE_ENABLED" | "FILE_PREVIEW_CACHE_DIR">;

const DEFAULT_CACHE_DIR = "data/uploads/preview-cache";

/** Whitelisted thumbnail widths (px). The route rejects anything else. */
export const THUMBNAIL_WIDTHS: readonly number[] = [64, 160, 320, 640, 1280];

export function previewCacheEnabled(config: PreviewCacheConfig): boolean {
  return config.FILE_PREVIEW_CACHE_ENABLED !== "false";
}

/** Parse a `?thumb=` value, returning the width only if it is whitelisted. */
export function parseThumbnailWidth(raw: string | null | undefined): number | undefined {
  if (!raw)
    return undefined;
  const n = Number(raw);
  return THUMBNAIL_WIDTHS.includes(n) ? n : undefined;
}

function cacheRoot(config: PreviewCacheConfig): string {
  const dir = config.FILE_PREVIEW_CACHE_DIR || DEFAULT_CACHE_DIR;
  return isAbsolute(dir) ? dir : resolve(ROOT_DIR, dir);
}

function thumbPath(config: PreviewCacheConfig, sha256: string, width: number): string {
  // Fan out by the sha256 prefix, mirroring the blob store layout.
  return resolve(cacheRoot(config), sha256.slice(0, 2), sha256.slice(2, 4), `${sha256}-w${width}.webp`);
}

async function readBlobBytes(storageKey: string): Promise<Uint8Array> {
  const stream = await getActiveDriver().getStream(storageKey);
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

async function writeCache(path: string, bytes: Uint8Array): Promise<void> {
  const dir = dirname(path);
  if (!existsSync(dir))
    mkdirSync(dir, { recursive: true, mode: 0o700 });
  await Bun.write(path, bytes);
}

/**
 * Return a cached WebP thumbnail of `blob` at `width`, generating it on a miss.
 * Returns `null` if the source bytes can't be decoded as an image (a corrupt or
 * unsupported file) so the caller can fall back to serving the original.
 */
export async function getThumbnail(
  config: PreviewCacheConfig,
  blob: { readonly sha256: string; readonly storageKey: string },
  width: number,
): Promise<Uint8Array<ArrayBuffer> | null> {
  const path = thumbPath(config, blob.sha256, width);
  const cached = Bun.file(path);
  if (await cached.exists())
    return new Uint8Array(await cached.arrayBuffer());

  try {
    const src = await readBlobBytes(blob.storageKey);
    // Copy into a fresh ArrayBuffer-backed view so it is a valid Response body.
    const bytes = new Uint8Array(await new Bun.Image(src).resize(width).webp().bytes());
    await writeCache(path, bytes);
    return bytes;
  }
  catch {
    return null;
  }
}
